# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: inmili <inmili@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/10 12:28:27 by inmili            #+#    #+#              #
#    Updated: 2024/01/13 18:08:17 by inmili           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC 				= cc
RM              = rm -rf
CFLAGS 			= -Wall -Wextra -Werror
NAME			= libft.a

SRCS			=	ft_isalnum.c ft_isprint.c ft_memcmp.c    \
					ft_strlcat.c ft_strncmp.c ft_substr.c ft_atoi.c ft_isalpha.c \
					 ft_memcpy.c   ft_strchr.c  ft_strlcpy.c \
					ft_strnstr.c ft_tolower.c ft_bzero.c   ft_isascii.c ft_memcpy.c \
					ft_memmove.c   ft_strdup.c  ft_strlen.c  ft_strrchr.c \
					ft_toupper.c ft_calloc.c  ft_isdigit.c ft_memchr.c  ft_memset.c  \
					ft_strjoin.c  ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c \
					ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c \
					ft_putnbr_fd.c 

SRCS_BONUS	= 	ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c ft_lstlast_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c \
			ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c

OBJS			= ${SRCS:.c=.o}
B_OBJS			= ${SRCS_BONUS:.c=.o}

all: 	${NAME}

${NAME}:	${OBJS}
	ar rcs ${NAME} $^
%o: %c libft.h
	${CC} ${CFLAGS} -c $< -o $@

bonus: ${OBJS} ${B_OBJS}
	ar rcs ${NAME} $^

clean:
	${RM} ${OBJS} ${B_OBJS}

fclean:	clean
	${RM} ${NAME}

re:	fclean all

.PHONY : all clean fclean re bonus
